'use client'
import checkIsPublicRouter from '@/functions/checkPublicRouter'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import PrivateRouter from '@/components/privateRouter/privateRouter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  const isPublicRouter = checkIsPublicRouter(pathname)
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        {isPublicRouter && children}
        {!isPublicRouter && <PrivateRouter>{children}</PrivateRouter>}
      </body>
    </html>
  )
}
