'use client'
import PrivateRouter from '@/components/privateRouter/privateRouter'
import checkIsPublicRouter from '@/functions/checkPublicRouter'
import type { Metadata } from 'next'
import { usePathname } from 'next/navigation'

/*export const metadata: Metadata = {
    title: 'TBCs',
    description: 'Generated by create next app',
    icons: {
        icon: '/logo-rubeus.png'

    }
}*/

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    const pathname = usePathname()
  
    const isPublicRouter = checkIsPublicRouter(pathname)
    return (
      <html lang="pt-br">
        <body>
          {isPublicRouter && children}
          {!isPublicRouter && <PrivateRouter>{children}</PrivateRouter>}
        </body>
      </html>
    )
  }
