import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'TBCs',
    description: 'Generated by create next app',
    icons: {
        icon: '/logo-rubeus.png'

    }
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="pt-br">
            <body >{children}</body>
        </html>
    )
}
